name: run-test-suite-on-pr
on: [pull-request]
jobs:
    run-test-suite:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/node@v1
            - run: npm install
            - run: npm run test
