name: run-test-suite-on-pr
on: [pull_request]
jobs:
    run-test-suite:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
            - run: npm ci
            - run: npm run test
